/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package it.unibas.lunatic.gui.window.cellgroup;

import it.unibas.lunatic.gui.R;
import javax.swing.JPanel;
import org.openide.awt.Actions;

/**
 *
 * @author Tony
 */
public class CellGroupDetails extends javax.swing.JPanel implements Cloneable {

    /**
     * Creates new form CellGroupDetails
     */
    public CellGroupDetails() {
        initComponents();
        editButton.setAction(Actions.forID("Edit", R.ActionId.EDIT_CELL_GROUP_VALUE));
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        lblValue = new javax.swing.JLabel();
        cgValue = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        org.openide.awt.Mnemonics.setLocalizedText(lblValue, org.openide.util.NbBundle.getMessage(CellGroupDetails.class, "CellGroupDetails.lblValue.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(cgValue, org.openide.util.NbBundle.getMessage(CellGroupDetails.class, "CellGroupDetails.cgValue.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(editButton, org.openide.util.NbBundle.getMessage(CellGroupDetails.class, "CellGroupDetails.editButton.text")); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(lblValue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cgValue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 361, Short.MAX_VALUE)
                .addComponent(editButton)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValue)
                    .addComponent(cgValue)
                    .addComponent(editButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(mainPanel);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cgValue;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel lblValue;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables

    public void setCellGroupValue(String displayName) {
        cgValue.setText(displayName);
    }
}
