/*****************************************************************************
JEP 2.4.1, Extensions 1.1.1
April 30 2007
(c) Copyright 2007, Nathan Funk and Richard Morris
See LICENSE-*.txt for license information.
 *****************************************************************************/
/* Generated By:JJTree: Do not edit this line. ASTVarNode.java */
package org.nfunk.jep;

/**
 * Variable Node
 */
public class ASTVarNode extends SimpleNode {

    private String varName;

    public ASTVarNode(int id) {
        super(id);
        varName = null;
    }

    public ASTVarNode(Parser p, int id) {
        super(p, id);
    }

    @Override
    public Object clone() {
        ASTVarNode clone = (ASTVarNode) super.clone();
        return clone;
    }

    /**
     * Accept the visitor.
     */
    public Object jjtAccept(ParserVisitor visitor, Object data) throws ParseException {
        return visitor.visit(this, data);
    }

    @Override
    public void accept(IExpressionVisitor visitor) {
        visitor.visitASTVarNode(this);
    }
    
    public void setVarName(String name) {
        this.varName = name;
    }

    /**
     * Returns the name of the variable.
     */
    public String getVarName() {
        return varName;
    }
            
    /**
     * Creates a string containing the variable's name and value
     */
    public String toString() {
        String temp = "Variable: \"" + getVarName() + "\"";
        return temp;
    }
}
