/* Generated By:JJTree: Do not edit this line. /Users/singularsys/Documents/workspace/jep-newcvs/src/org/nfunk/jep/ParserVisitor.java */
package org.nfunk.jep;

public interface IExpressionVisitor {

    public void visitSimpleNode(SimpleNode node);

    public void visitASTStart(ASTStart node);

    public void visitASTFunNode(ASTFunNode node);

    public void visitASTVarNode(ASTVarNode node);

    public void visitASTConstant(ASTConstant node);

    Object getResult();
}
