package it.unibas.lunatic.gui.window.chase;

import it.unibas.lunatic.gui.ExplorerTopComponent;
import it.unibas.lunatic.gui.R;

import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.nodes.Node;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//it.unibas.lunatic.gui//DeChaseResult//EN",
        autostore = false)
@TopComponent.Description(
        preferredID = R.Window.DE_CHASE_RESULT,
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "explorer", openAtStartup = false)
//@ActionID(category = "Window", id = "it.unibas.lunatic.gui.action.OpenDeChaseResultView")
//@ActionReference(path = "Menu/Window" /*, position = 333 */)
//@TopComponent.OpenActionRegistration(
//        displayName = "#CTL_DeChaseResultAction",
//        preferredID = R.Window.DE_CHASE_RESULT)
@Messages({
    "CTL_DeChaseResultAction=Data exchange result",
    "CTL_DeChaseResultTopComponent=Data exchange result",
    "HINT_DeChaseResultTopComponent=Data exchange result window"
})
public final class DeChaseResultTopComponent extends ExplorerTopComponent {

    public DeChaseResultTopComponent() {
        initComponents();
        setName(Bundle.CTL_DeChaseResultTopComponent());
        setToolTipText(Bundle.HINT_DeChaseResultTopComponent());
        associateExplorerLookup();
        treeView.setRootVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        treeView = new org.openide.explorer.view.BeanTreeView();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
        add(treeView);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openide.explorer.view.BeanTreeView treeView;
    // End of variables declaration//GEN-END:variables
    private DeChaseListener chaseListener = new DeChaseListener();

    @Override
    public void componentOpened() {
        chaseListener.register(this);
    }

    @Override
    public void componentClosed() {
        chaseListener.remove();
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.3");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    public void setRootContext(Node nodeDelegate) {
        explorer.setRootContext(nodeDelegate);
        treeView.setRootVisible(true);
    }

    @Override
    public void removeRootContext() {
        throw new UnsupportedOperationException("Not supported yet.");
    }
    
    
}
