package it.unibas.lunatic.gui.window.chase;

import it.unibas.lunatic.gui.ExplorerTopComponent;
import org.openide.explorer.ExplorerManager;
import org.openide.nodes.Node;

/**
 *
 * @author Tony
 */
public class McAnchestorsComponent extends ExplorerTopComponent {


    /**
     * Creates new form ResultStackPanel
     */
    public McAnchestorsComponent() {
        initComponents();
        treeView.setRootVisible(false);
        associateExplorerLookup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        treeView = new org.openide.explorer.view.BeanTreeView();

        setLayout(new java.awt.BorderLayout());

        org.openide.awt.Mnemonics.setLocalizedText(titleLabel, org.openide.util.NbBundle.getMessage(McAnchestorsComponent.class, "McAnchestorsComponent.titleLabel.text")); // NOI18N
        titlePanel.add(titleLabel);

        add(titlePanel, java.awt.BorderLayout.PAGE_START);
        add(treeView, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    private org.openide.explorer.view.BeanTreeView treeView;
    // End of variables declaration//GEN-END:variables

    @Override
    public ExplorerManager getExplorerManager() {
        return explorer;
    }

    @Override
    public void setRootContext(Node node) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void removeRootContext() {
        throw new UnsupportedOperationException("Not supported yet.");
    }
}
