/*                         
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package it.unibas.lunatic.gui.window.chase;

import it.unibas.lunatic.gui.model.McChaseResult;
import it.unibas.lunatic.gui.node.chase.mc.stack.FlatChaseTreeRoot;
import javax.swing.ActionMap;
import javax.swing.JComponent;
import javax.swing.JPanel;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.util.Lookup;

/**
 *
 * @author Tony
 */
public class McStackNodesViewPanel extends JPanel implements McResultView {
    
    private McAnchestorsComponent bottomPanel = new McAnchestorsComponent();
    private ExplorerManager explorerManager;

    /**
     * Creates new form McStackViewPanel
     */
    public McStackNodesViewPanel() {
        initComponents();
        splitPane.setBottomComponent(bottomPanel);
        treeView.setRootVisible(false);
    }
    private ChaseStackGenerator selectionListener = new ChaseStackGenerator();
    private McResultUpdateListener listener = new McResultUpdateListener();
    
    @Override
    public void componentOpened() {
        selectionListener.register(bottomPanel);
        listener.register(this);
    }
    
    @Override
    public void componentClosed() {
        selectionListener.remove();
        listener.remove();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        treeView = new org.openide.explorer.view.BeanTreeView();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        splitPane.setDividerSize(7);
        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        splitPane.setResizeWeight(0.8);
        splitPane.setTopComponent(treeView);

        add(splitPane);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane splitPane;
    private org.openide.explorer.view.BeanTreeView treeView;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onChaseResultUpdate(McChaseResult result) {
        explorerManager.setRootContext(new FlatChaseTreeRoot(result));
    }
    
    @Override
    public void onChaseResultClose() {
    }
    
    @Override
    public JComponent toComponent() {
        return this;
    }
    
    @Override
    public void addNotify() {
        super.addNotify();
        this.explorerManager = ExplorerManager.find(this);
    }
}
